# Generated by Django 4.2.1 on 2023-05-29 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('69cc6ed3-be14-4909-9f08-1a8c0dff8678'), editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
                ('bottles', models.IntegerField(default=0)),
                ('bottles_today', models.IntegerField(default=0)),
            ],
        ),
    ]
