# Generated by Django 4.2.1 on 2023-05-29 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ecosite', '0002_alter_accountmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bef1efb7-bb43-4e7f-a1f4-85b0d323b477'), editable=False, primary_key=True, serialize=False),
        ),
    ]
